#Passed In Attributes #Map Constants
ROWS = 15
COLS = 15
TILESIZE = 48
SIDE_PANEL = 300
SCREEN_WIDTH = TILESIZE * COLS
SCREEN_HEIGHT = TILESIZE * ROWS
FPS = 60
HEALTH = 100
MONEY = 650
TOTALLEVELS = 15

#Turret Constants
TURRETLEVELS = 4
BUYCOST = 200
UPGRADECOST = 100
ANIMATIONSTEPS = 8
ANIMATIONDELAY = 15
DAMAGE = 5
KILLREWARD = 2
WAVEREAWRD = 100

#Enemy Constants
SPAWNCOOLDOWN = 800
